### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by abrozzi** [rrwick/SRST2-table-from-assemblies#3]
Dear Ryan,

referred to this https://github.com/katholt/Kaptive/issues/15#issuecomment-866510703:

 ```
python SRST2-table-from-assemblies/srst2_table_from_assemblies.py 
--assemblies SRST2-table-from-assemblies/example_data/sample* 
--gene_db SRST2-table-from-assemblies/example_data/gene_db.mfasta 
--output test
 ```

gives me the following error:

 ```
Traceback (most recent call last):
  File "SRST2-table-from-assemblies/srst2_table_from_assemblies.py", line 335, in <module>
    main()
  File "SRST2-table-from-assemblies/srst2_table_from_assemblies.py", line 52, in main
    blast_results = blast_assembly(assembly, args.gene_db, args.algorithm, unique_allele_symbols)
  File "SRST2-table-from-assemblies/srst2_table_from_assemblies.py", line 164, in blast_assembly
    for line in blast_results_iterator(out):
  File "SRST2-table-from-assemblies/srst2_table_from_assemblies.py", line 255, in blast_results_iterator
    nextnl = results.find('\n', prevnl + 1)
TypeError: a bytes-like object is required, not 'str'
```

Thank you!
-A

**Comment by abrozzi** [comment]
Resolved: **It works with python2.7.**

It crashes with python3.8.

This is because here at line 255:

```
 http://stackoverflow.com/questions/3054604/iterate-over-the-lines-of-a-string
def blast_results_iterator(results):
    prevnl = -1
    while True:  
      nextnl = results.find('\n', prevnl + 1)
      if nextnl < 0: break
      yield results[prevnl + 1:nextnl]
      prevnl = nextnl
```
python2.7 and python3.8 treats differently bytes and string.

A possible solution to make it version independent would be to save somewhere the output of blastn and read it as tab separated values table.

my two cents,
Alex

**Comment by ronaldgevern** [comment]
The reason for this error is that in Python 3, strings are Unicode, but when transmitting on the network, the data needs to be bytes instead. We can convert [bytes to string](http://net-informations.com/python/iq/byte.htm) using bytes class decode() instance method, So you need to decode the bytes object to produce a string. In Python 3 , the default encoding is "utf-8" , so you can use directly:

`b"python byte to string".decode("utf-8")`

Python makes a clear distinction between bytes and strings . Bytes objects contain raw data — a sequence of octets — whereas strings are Unicode sequences . Conversion between these two types is explicit: you encode a string to get bytes, specifying an encoding (which defaults to UTF-8); and you decode bytes to get a string. Clients of these functions should be aware that such conversions may fail, and should consider how failures are handled.

**Comment by PaynDita** [comment]
a bytes-like object is required not 'str' 


simply add .decode()
eg;

 If keyword in load:

	return load

Error:

if keyword in load:

TypeError: a bytes-like object is required not 'str'


solution:

If keyword in load.decode():

	return load

For easy understanding click the below link:
https://payndita.wixsite.com/it-garage/post/a-bytes-like-object-is-required-not-str
